### ISSUE TITLE
running on colab

### ISSUE THREAD

**Issue by jagarju** [joeaelkhoury/Mamba-Demo#1]
I tried to run this code on google colab T4 and it gave me an error after i changed the dtype to bfloat

model = MambaLMHeadModel.from_pretrained(os.path.expanduser("state-spaces/mamba-2.8b"), device="cuda", dtype=torch.bfloat16)

but i got this error can you please suggest solution to run it

thank you

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-71c2a6f9c819> in <cell line: 8>()
      6         return_dict_in_generate=True, output_scores=True,
      7         enable_timing=False, temperature=0.1, top_k=10, top_p=0.2,)
----> 8 out = fn()
      9 print(tokenizer.decode(out[0][0]))

27 frames
<string> in _layer_norm_fwd_1pass_kernel(X, Y, W, B, RESIDUAL, RESIDUAL_OUT, Mean, Rstd, stride_x_row, stride_y_row, stride_res_row, stride_res_out_row, N, eps, IS_RMS_NORM, BLOCK_N, HAS_RESIDUAL, STORE_RESIDUAL_OUT, HAS_BIAS, grid, num_warps, num_stages, extern_libs, stream, warmup, device, device_type)

/usr/local/lib/python3.10/dist-packages/triton/compiler/compiler.py in ptx_to_cubin(ptx, arch)
    148     '''
    149     ptxas, _ = path_to_ptxas()
--> 150     return compile_ptx_to_cubin(ptx, ptxas, arch)
    151 
    152 

RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/compile-ptx-src-0ec71f, line 984; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 984; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 986; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 986; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 988; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 988; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 990; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 990; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 992; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 992; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 994; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 994; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 996; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 996; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 998; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 998; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1024; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1026; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1026; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1028; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1028; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1030; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1030; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1032; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1032; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1034; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1034; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1036; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1036; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1038; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1038; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1040; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1040; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1042; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1042; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1044; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1044; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1046; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1046; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1048; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1048; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1050; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1050; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1052; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1052; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1054; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1054; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1056; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1056; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1058; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1058; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1060; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1060; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1062; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1062; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1064; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1064; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1066; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1066; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1068; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1068; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1070; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 1070; error   : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2741; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2741; error   : Feature 'cvt.bf16.f32' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2743; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2743; error   : Feature 'cvt.bf16.f32' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2745; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2745; error   : Feature 'cvt.bf16.f32' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2747; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2747; error   : Feature 'cvt.bf16.f32' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2749; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2749; error   : Feature 'cvt.bf16.f32' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2751; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2751; error   : Feature 'cvt.bf16.f32' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2753; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2753; error   : Feature 'cvt.bf16.f32' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2755; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2755; error   : Feature 'cvt.bf16.f32' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2757; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2757; error   : Feature 'cvt.bf16.f32' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2759; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2759; error   : Feature 'cvt.bf16.f32' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2761; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2761; error   : Feature 'cvt.bf16.f32' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2763; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2763; error   : Feature 'cvt.bf16.f32' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-0ec71f, line 2765; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas fatal   : Ptx assembly aborted due to errors

**Comment by joeaelkhoury** [comment]
i suggest to change dtype to dtype=torch.float16 and try to run it on A100

**Comment by jagarju** [comment]
thank you
